
export const SOCKET_CHANNELS = {
    NOTIFICATIONS: "myNotification",
    SYNC_PROJECT_STATUS_CHANGED_REQUEST: "syncNewProjectChangeStatus",
    SYNC_PROJECT_STATUS_CHANGED_DATA: "syncDataProjectChangeStatus",
    SYSTEM_NOTIFICATIONS: "globalNotify",
    PROJECT_CREATED: "projectCreated",
    PROJECT_DUPLICATED: "projectDuplicated",
    PROJECT_UPDATED: "projectUpdated",
    PROJECT_STATUS_UPDATED: "projectChangedStatus",
    PROJECT_STATUS_UPDATED_REQUEST: "projectRequestChangedStatus",
    PROJECT_CLOSED: "projectClosed",
    PROJECT_REOPENED: "projectReopened",
    PROJECT_TRASHED: "projectTrashed",
    PROJECT_DELETED: "projectDeleted",
    PROJECT_RESTORED: "projectRestored",
    ADD_DEPARTMENT_TO_PROJECT: "addDepartmentToProject",
    FILE_UPLOADED: "fileUploaded",
    COMMENT_CREATED: "commentCreated",
    COMMENT_TAGGED: "taggedUser",
    TASK_CREATED: "taskCreated",
    TASK_STARTED: "taskStarted",
    TASK_COMPLETED: "taskCompleted",
    TASK_TRASHED: "taskTrashed",
    TASK_DELETED: "taskDeleted",
    APPROVAL_REQUEST: "requestActiveAccount",
}

export const NOTIFICATION_TYPE = {
    NORMAL: 1,
    IMPORTANT: 2,
}

export const NOTIFICATIONS = {
    SYSTEM: {
        CREATED: 1,
    },
    PROJECTS: {
        CREATED: 21,
        UPDATED: 22,
        CLOSED: 23,
        REOPENED: 24,
        DELETED: 25,
        ADD_DEPARTMENT: 26,
        FILE_UPLOADED: 27,
        TRASHED: 28,
        RESTORED: 29,
        LEADER_CREATED: 30,
        LEADER_DELETED: 31,
        DEPARTMENT_LEADER_CREATED: 32,
        DEPARTMENT_LEADER_DELETED: 33,
        PHASE_LEADER_CREATED: 34,
        PHASE_LEADER_DELETED: 35,
        DUPLICATED: 36,
        STATUS_UPDATED_REQUEST: 37,
        STATUS_UPDATED: 38,
        GUEST_CREATED: 101,
        GUEST_DELETED: 102,
        DEPARTMENT_GUEST_CREATED: 103,
        DEPARTMENT_GUEST_DELETED: 104,
        PHASE_GUEST_CREATED: 105,
        PHASE_GUEST_DELETED: 106,
        TASK_GUEST_CREATED: 107,
        TASK_GUEST_DELETED: 108,
    },
    TASKS: {
        CREATED: 41,
        STARTED: 42,
        COMPLETED: 43,
        DELAYED: 44,
        DELETED: 45,
        TRASHED: 46,
        START_REMINDER: 47,
        LEADER_CREATED: 48,
        LEADER_DELETED: 49,
        ASSIGNEE_CREATED: 50,
        ASSIGNEE_DELETED: 51,
        RESPONSIBLE_CREATED: 57,
        ACCOUNTABLE_CREATED: 58,
        INFORMED_CREATED: 59,
        CONSULTED_CREATED: 60,
        RESPONSIBLE_DELETED: 53,
        ACCOUNTABLE_DELETED: 54,
        INFORMED_DELETED: 55,
        CONSULTED_DELETED: 56,
        UPDATED: 109,
        STARTED_LEADER: 110,
        COMPLETED_WORKER: 111,
        DELAYED_LEADER: 112,
        DELAYED_DEPEND: 113,
        REQUEST: 114,
        REJECTED: 115,
        PROGRESS: 116,
        REJECTED_FOLLOW: 117,
        PROGRESS_DEPEND: 118,
    },
    PHASE: {
        CREATED: 140,
        UPDATED: 141,
        DELETED: 142,
    },
    DEPARTMENT: {
        UPDATED: 130,
        DELETED: 131,
        RESTORED: 132,
    },
    COMMENTS: {
        CREATED: 61,
        MENTIONED: 62,
    },
    ACCOUNTS: {
        APPROVED: 81,
    },
    MEETINGS: {
        UPDATED: 121,
        DELETED: 122,
        INVITED: 123,
        REMOVE_INVITED: 124,
        CONFIRMED: 125,
        UNCONFIRMED: 126,
        REMIND_MEETING: 127,
        REMIND_MEETING_END: 128,
    },
    GROUPS: {
        LEADER_CREATED: 150,
        LEADER_DELETED: 151,
        USER_CREATED: 152,
        USER_DELETED: 153,
        UPDATED: 154,
        DELETED: 155,
    },
    DAILY_REPORTS: {
        CREATED: 160,
        UPDATED: 161,
        DELETED: 162,
        UPDATED_STATUS: 163,
    },
    OVERTIME: {
        CREATED: 170,
        APPROVED: 171,
        REJECTED: 172,
        ADMIN_UPDATED: 173,
    },
    LEAVE_REQUEST: {
        CREATED: 180,
        APPROVED: 181,
        REJECTED: 182,
        ADMIN_UPDATED: 183,
    },
    WORK_TIME: {
        INCORRECT: 190,
    },
}